// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhVSoYcyxSf9QtjuszPtI_oATeDBZ5TXQ',
    appId: '1:983563444594:android:6762aee5655ee1de913deb',
    messagingSenderId: '983563444594',
    projectId: 'bloggie-91b87',
    databaseURL: 'https://bloggie-91b87-default-rtdb.firebaseio.com',
    storageBucket: 'bloggie-91b87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU17lQq-5hQIEoxb9OGpB0D7Zi-Sy8diU',
    appId: '1:983563444594:ios:292f99194fff194b913deb',
    messagingSenderId: '983563444594',
    projectId: 'bloggie-91b87',
    databaseURL: 'https://bloggie-91b87-default-rtdb.firebaseio.com',
    storageBucket: 'bloggie-91b87.appspot.com',
    iosClientId: '983563444594-t7r6jo8ttu4smeqjqdg7tl3jb2kripku.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloggie',
  );
}
